In [8]:
# Importar librerías

In [9]:
import pandas as pd

In [10]:
import numpy as np

In [11]:
# Leer archivo csv

In [12]:
df = pd.read_csv('/content/netflix_titles.csv')

In [13]:
# Mostrar primeras filas

In [14]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [15]:
# Tomar 5 registros

In [16]:
muestra = df[['title','release_year','type']].head(5)

In [17]:
muestra

                   title  release_year     type
0   Dick Johnson Is Dead          2020    Movie
1          Blood & Water          2021  TV Show
2              Ganglands          2021  TV Show
3  Jailbirds New Orleans          2021  TV Show
4           Kota Factory          2021  TV Show

In [18]:
# Convertir tipo a booleano

In [19]:
titulo1 = [
    muestra.iloc[0]['title'],
    int(muestra.iloc[0]['release_year']),
    muestra.iloc[0]['type'] == 'Movie'
]

In [20]:
titulo2 = [
    muestra.iloc[1]['title'],
    int(muestra.iloc[1]['release_year']),
    muestra.iloc[1]['type'] == 'Movie'
]

In [21]:
titulo3 = [
    muestra.iloc[2]['title'],
    int(muestra.iloc[2]['release_year']),
    muestra.iloc[2]['type'] == 'Movie'
]

In [22]:
titulo4 = [
    muestra.iloc[3]['title'],
    int(muestra.iloc[3]['release_year']),
    muestra.iloc[3]['type'] == 'Movie'
]

In [23]:
titulo5 = [
    muestra.iloc[4]['title'],
    int(muestra.iloc[4]['release_year']),
    muestra.iloc[4]['type'] == 'Movie'
]

In [24]:
print(titulo1)
print(titulo2)
print(titulo3)
print(titulo4)
print(titulo5)

['Dick Johnson Is Dead', 2020, True]
['Blood & Water', 2021, False]
['Ganglands', 2021, False]
['Jailbirds New Orleans', 2021, False]
['Kota Factory', 2021, False]

In [25]:
# Catálogo provisional

In [26]:
catalogo_provisional = [
    titulo1,
    titulo2,
    titulo3,
    titulo4,
    titulo5
]

In [27]:
catalogo_provisional

[['Dick Johnson Is Dead', 2020, True],
 ['Blood & Water', 2021, False],
 ['Ganglands', 2021, False],
 ['Jailbirds New Orleans', 2021, False],
 ['Kota Factory', 2021, False]]

In [28]:
# Segundo y tercer título

In [29]:
sub_lista = catalogo_provisional[1:3]

In [30]:
sub_lista

[['Blood & Water', 2021, False], ['Ganglands', 2021, False]]

In [31]:
# Último título

In [32]:
print(catalogo_provisional[-1])

['Kota Factory', 2021, False]

In [33]:
# Agregar un nuevo titulo

In [34]:
nuevo_titulo = [
    "Mi Pelicula Favorita",
    2026,
    True
]

In [35]:
catalogo_provisional.append(nuevo_titulo)

In [36]:
catalogo_provisional

[['Dick Johnson Is Dead', 2020, True],
 ['Blood & Water', 2021, False],
 ['Ganglands', 2021, False],
 ['Jailbirds New Orleans', 2021, False],
 ['Kota Factory', 2021, False],
 ['Mi Pelicula Favorita', 2026, True]]

In [37]:
# Eliminar un titulo

In [38]:
catalogo_provisional.remove(titulo2)

In [39]:
catalogo_provisional

[['Dick Johnson Is Dead', 2020, True],
 ['Ganglands', 2021, False],
 ['Jailbirds New Orleans', 2021, False],
 ['Kota Factory', 2021, False],
 ['Mi Pelicula Favorita', 2026, True]]

In [40]:
# Tomar solo películas

In [41]:
peliculas = df[df['type'] == 'Movie']

In [42]:
peliculas[['title','duration']].head(10)

                                                title duration
0                                Dick Johnson Is Dead   90 min
6                    My Little Pony: A New Generation   91 min
7                                             Sankofa  125 min
9                                        The Starling  104 min
12                                       Je Suis Karl  127 min
13                   Confessions of an Invisible Girl   91 min
16  Europe's Most Dangerous Man: Otto Skorzeny in ...   67 min
18                                          Intrusion   94 min
22                                    Avvai Shanmughi  161 min
23       Go! Go! Cory Carson: Chrissy Takes the Wheel   61 min

In [43]:
# Limpiar duración

In [44]:
duraciones = []

for d in peliculas['duration'].head(10):
    numero = int(d.replace(' min',''))
    duraciones.append(numero)

In [45]:
duraciones

[90, 91, 125, 104, 127, 91, 67, 94, 161, 61]

In [46]:
# Crear ndarray

In [47]:
duraciones_np = np.array(duraciones)

In [48]:
duraciones_np

array([ 90,  91, 125, 104, 127,  91,  67,  94, 161,  61])

In [49]:
# Buffer del 5%

In [50]:
buffer_5 = duraciones_np * 1.05

In [51]:
buffer_5

array([ 94.5 ,  95.55, 131.25, 109.2 , 133.35,  95.55,  70.35,  98.7 ,
       169.05,  64.05])

In [52]:
# Duración ideal

In [53]:
duracion_ideal = np.array([100]*10)

In [54]:
duracion_ideal

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [55]:
# Desviación

In [56]:
desviacion = duraciones_np - duracion_ideal

In [57]:
desviacion

array([-10,  -9,  25,   4,  27,  -9, -33,  -6,  61, -39])

In [58]:
# Estadísticas

In [59]:
print("Promedio:", np.mean(duraciones_np))
print("Máximo:", np.max(duraciones_np))
print("Mínimo:", np.min(duraciones_np))

Promedio: 101.1
Máximo: 161
Mínimo: 61

In [60]:
# Crear lista_rrss

In [61]:
datos = df[
    ['show_id','type','title','release_year']
].head(10)

In [62]:
lista_rrss = datos.values.tolist()

In [63]:
lista_rrss

[['s1', 'Movie', 'Dick Johnson Is Dead', 2020],
 ['s2', 'TV Show', 'Blood & Water', 2021],
 ['s3', 'TV Show', 'Ganglands', 2021],
 ['s4', 'TV Show', 'Jailbirds New Orleans', 2021],
 ['s5', 'TV Show', 'Kota Factory', 2021],
 ['s6', 'TV Show', 'Midnight Mass', 2021],
 ['s7', 'Movie', 'My Little Pony: A New Generation', 2021],
 ['s8', 'Movie', 'Sankofa', 1993],
 ['s9', 'TV Show', 'The Great British Baking Show', 2021],
 ['s10', 'Movie', 'The Starling', 2021]]

In [64]:
df_rrss = pd.DataFrame(
    lista_rrss,
    columns=[
        'ID',
        'Tipo',
        'Título',
        'Año'
    ]
)

In [65]:
df_rrss

    ID     Tipo                            Título   Año
0   s1    Movie              Dick Johnson Is Dead  2020
1   s2  TV Show                     Blood & Water  2021
2   s3  TV Show                         Ganglands  2021
3   s4  TV Show             Jailbirds New Orleans  2021
4   s5  TV Show                      Kota Factory  2021
5   s6  TV Show                     Midnight Mass  2021
6   s7    Movie  My Little Pony: A New Generation  2021
7   s8    Movie                           Sankofa  1993
8   s9  TV Show     The Great British Baking Show  2021
9  s10    Movie                      The Starling  2021

In [66]:
print("Cantidad de registros:", len(df_rrss))

Cantidad de registros: 10

In [67]:
df_rrss.head()

   ID     Tipo                 Título   Año
0  s1    Movie   Dick Johnson Is Dead  2020
1  s2  TV Show          Blood & Water  2021
2  s3  TV Show              Ganglands  2021
3  s4  TV Show  Jailbirds New Orleans  2021
4  s5  TV Show           Kota Factory  2021