# Punto 1:

# Intro python data science
## Práctica 05: pandas dataframe

Vamos a ver cómo:
* Punto 1: Crear dataframes
* Punto 2: Seleccionar elementos
* Punto 3: Ordenar columnas

In [69]:
# importar pandas

In [70]:
import pandas as pd

In [71]:
# datos de RRSS 2020

In [72]:
fbk = ['Facebook', 2449, True, 2006]
twt = ['Twitter', 339, False, 2006]
ig = ['Instagram', 1000, True, 2010]
yt = ['YouTube', 2000, False, 2005]
lkn = ['LinkedIn', 663, False, 2003]
wsp = ['WhatsApp', 1600, True, 2009]

In [73]:
# crear dataframe a partir de listas

In [74]:
lista_rrss = [fbk, twt, ig, yt, lkn, wsp]

In [75]:
df_rrss = pd.DataFrame(lista_rrss,
                       columns = ['Nombre', 'Cantidad', 'ES_FBK', 'Año'])

In [76]:
df_rrss

      Nombre  Cantidad  ES_FBK   Año
0   Facebook      2449    True  2006
1    Twitter       339   False  2006
2  Instagram      1000    True  2010
3    YouTube      2000   False  2005
4   LinkedIn       663   False  2003
5   WhatsApp      1600    True  2009

In [77]:
# crear dataframe vacio

In [78]:
df_vacio = pd.DataFrame(columns = ['Nombre', 'Cantidad', 'ES_FBK', 'Año'])

In [79]:
df_vacio

Empty DataFrame
Columns: [Nombre, Cantidad, ES_FBK, Año]
Index: []

In [80]:
new_row = pd.DataFrame([{'Nombre' : 'Facebook',
                            'Cantidad' : 2449,
                            'ES_FBK' : True,
                            'Año' : 2006}])
df_vacio = pd.concat([df_vacio, new_row], ignore_index=True)

In [81]:
df_vacio

     Nombre Cantidad ES_FBK   Año
0  Facebook     2449   True  2006

In [82]:
new_row = pd.DataFrame([{'Nombre' : 'Instagram',
                            'Cantidad' : 1000,
                            'ES_FBK' : True,
                            'Año' : 2010}])
df_vacio = pd.concat([df_vacio, new_row], ignore_index=True)

In [83]:
df_vacio

      Nombre Cantidad ES_FBK   Año
0   Facebook     2449   True  2006
1  Instagram     1000   True  2010

In [84]:
df_vacio

      Nombre Cantidad ES_FBK   Año
0   Facebook     2449   True  2006
1  Instagram     1000   True  2010

In [85]:
# en proximos videos como crear dataframes a partir de csv o excel

# Punto 2:

In [86]:
# seleccionar elementos: .loc vs .iloc

In [87]:
df_rrss

      Nombre  Cantidad  ES_FBK   Año
0   Facebook      2449    True  2006
1    Twitter       339   False  2006
2  Instagram      1000    True  2010
3    YouTube      2000   False  2005
4   LinkedIn       663   False  2003
5   WhatsApp      1600    True  2009

In [88]:
# seleccionar un elemento por etiquetas

In [89]:
df_rrss.loc[1,'Nombre']

'Twitter'

In [90]:
df_rrss.loc[4, 'Nombre']

'LinkedIn'

In [91]:
# seleccionar un elemento por número

In [92]:
df_rrss.iloc[1,0]

'Twitter'

In [93]:
df_rrss.iloc[3,0]

'YouTube'

In [94]:
# seleccionar por columnas/fila

In [103]:
df_rrss['Nombre']

0     Facebook
1      Twitter
2    Instagram
3      YouTube
4     LinkedIn
5     WhatsApp
Name: Nombre, dtype: object

In [105]:
df_rrss["Año"]

0    2006
1    2006
2    2010
3    2005
4    2003
5    2009
Name: Año, dtype: int64

In [106]:
df_rrss.iloc[4]

Nombre      LinkedIn
Cantidad         663
ES_FBK         False
Año             2003
Name: 4, dtype: object

In [96]:
# seleccionar por condicion booleana

In [107]:
df_rrss['Cantidad'] > 1500

0     True
1    False
2    False
3     True
4    False
5     True
Name: Cantidad, dtype: bool

In [111]:
df_rrss[df_rrss['Cantidad'] > 1500]

     Nombre  Cantidad  ES_FBK   Año
0  Facebook      2449    True  2006
3   YouTube      2000   False  2005
5  WhatsApp      1600    True  2009

In [116]:
df_rrss[df_rrss['Cantidad'] >= 2000]

     Nombre  Cantidad  ES_FBK   Año
0  Facebook      2449    True  2006
3   YouTube      2000   False  2005

# Punto 3:

In [97]:
# Como ordenar columnas

In [98]:
# ordenar modo ascendente: de menor a mayor

In [99]:
# ordenar descendente: de mayor a menor

In [100]:
# ordenar por dos valores

In [101]:
# ordenar por dos columnas