In [1]:
# importar pandas
import pandas as pd

In [2]:
# caso 1: datos separados por coma

In [3]:
pd.read_csv('/content/datos_rrss_t1(1).csv')

      Nombre  Cantidad     ES_FBK  Anio
0   Facebook      2449  VERDADERO  2006
1    Twitter       339      FALSO  2006
2  Instagram      1000  VERDADERO  2010
3    YouTube      2000      FALSO  2005
4   LinkedIn       663      FALSO  2003
5   WhatsApp      1600  VERDADERO  2009

In [4]:
# caso 2: datos separados por puntos y comas

In [5]:
pd.read_csv('/content/datos_rrss_t2(1).csv')

     Nombre;Cantidad;ES_FBK;Anio
0   Facebook;2449;VERDADERO;2006
1         Twitter;339;FALSO;2006
2  Instagram;1000;VERDADERO;2010

In [6]:
pd.read_csv('/content/datos_rrss_t2(1).csv',
            sep=';')

      Nombre  Cantidad     ES_FBK  Anio
0   Facebook      2449  VERDADERO  2006
1    Twitter       339      FALSO  2006
2  Instagram      1000  VERDADERO  2010

In [ ]:
# caso 3: no hay nombres de columnas

In [8]:
pd.read_csv('/content/datos_rrss_t3(1).csv')

    Facebook  2449  VERDADERO  2006
0    Twitter   339      FALSO  2006
1  Instagram  1000  VERDADERO  2010
2    YouTube  2000      FALSO  2005
3   LinkedIn   663      FALSO  2003
4   WhatsApp  1600  VERDADERO  2009

In [7]:
pd.read_csv('/content/datos_rrss_t3(1).csv',
            header=None,
            names = ['Nombre', 'Cantidad', 'ES_FBK', 'Año'])

      Nombre  Cantidad     ES_FBK   Año
0   Facebook      2449  VERDADERO  2006
1    Twitter       339      FALSO  2006
2  Instagram      1000  VERDADERO  2010
3    YouTube      2000      FALSO  2005
4   LinkedIn       663      FALSO  2003
5   WhatsApp      1600  VERDADERO  2009