In [7]:
# importar pandas
import pandas as pd

In [8]:
# extraer ruta del archivo
path = 'datos_rrss.xlsx'

In [ ]:
# caso 1: datos completos en la primera hoja

In [6]:
pd.read_excel(path)

      Nombre  Cantidad  ES_FBK   Año
0   Facebook      2449    True  2006
1    Twitter       339   False  2006
2  Instagram      1000    True  2010
3    YouTube      2000   False  2005
4   LinkedIn       663   False  2003
5   WhatsApp      1600    True  2009

In [ ]:
# caso 2: los datos no están en la primera hoja

In [9]:
pd.read_excel(path,
              sheet_name = 'Hoja2')

      Nombre  Cantidad  ES_FBK   Año
0   Facebook      2449    True  2006
1    Twitter       339   False  2006
2  Instagram      1000    True  2010

In [ ]:
# caso 3: no hay nombres de columnas

In [12]:
pd.read_excel(path,
              sheet_name = 'Hoja3')

    Facebook  2449   True  2006
0    Twitter   339  False  2006
1  Instagram  1000   True  2010
2    YouTube  2000  False  2005
3   LinkedIn   663  False  2003
4   WhatsApp  1600   True  2009

In [11]:
pd.read_excel(path,
              sheet_name = 'Hoja3',
              header = None,
              names = ['Nombre', 'Cantidad', 'ES_FBK', 'Año'])

      Nombre  Cantidad  ES_FBK   Año
0   Facebook      2449    True  2006
1    Twitter       339   False  2006
2  Instagram      1000    True  2010
3    YouTube      2000   False  2005
4   LinkedIn       663   False  2003
5   WhatsApp      1600    True  2009